# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20161114_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
